version: '3'
services:
  db:
    image: postgres:11
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cohdex
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ['redis-server']
  adminer:
    image: adminer
    restart: 'no'
    ports:
      - 5051:8080
