export * from './home/Home'
export * from './strategies/Strategies'
export * from './create-strategy/CreateStrategy'
export * from './strategy/Strategy'
export * from './settings/Settings'
export * from './404/NotFound'
